# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - svc.yml
  - sm.yml
  - dashboards

images:
  - name: goharbor/harbor-exporter
    newName: registry.sighup.io/fury/goharbor/harbor-exporter
    newTag: v2.7.0

configMapGenerator:
  - name: exporter
    literals:
    - HARBOR_DATABASE_DBNAME=registry
    - HARBOR_DATABASE_HOST=database
    - HARBOR_DATABASE_MAX_IDLE_CONNS=50
    - HARBOR_DATABASE_MAX_OPEN_CONNS=100
    - HARBOR_DATABASE_PORT=5432
    - HARBOR_DATABASE_SSLMODE=disable
    - HARBOR_DATABASE_USERNAME=postgres
    - HARBOR_EXPORTER_CACHE_CLEAN_INTERVAL=14400
    - HARBOR_EXPORTER_CACHE_TIME=23
    - HARBOR_EXPORTER_METRICS_ENABLED=true
    - HARBOR_EXPORTER_METRICS_PATH=/metrics
    - HARBOR_EXPORTER_PORT=8001
    - HARBOR_METRIC_NAMESPACE=registry
    - HARBOR_METRIC_SUBSYSTEM=exporter
    - HARBOR_REDIS_NAMESPACE=jobservice_ns
    - HARBOR_REDIS_TIMEOUT=3600
    - HARBOR_REDIS_URL=redis://redis:6379/1
    - HARBOR_SERVICE_HOST=core
    - HARBOR_SERVICE_PORT=80
    - HARBOR_SERVICE_SCHEME=http
    - HTTP_PROXY=""
    - HTTPS_PROXY=""
    - LOG_LEVEL=info
    - NO_PROXY=core,jobservice,database,chartmuseum,trivy,notary-server,notary-signer,registry,portal,exporter,127.0.0.1,localhost,.local,.internal

secretGenerator:
  - name: exporter
    literals:
      - HARBOR_ADMIN_PASSWORD=Harbor12345
      - HARBOR_DATABASE_PASSWORD=changeit